package com.example.springawsdynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "users")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey(attributeName="username") //sort key
    private String username;
    @DynamoDBAttribute
    private String surname;
    @DynamoDBAttribute
    private int age;

    @DynamoDBAttribute
    private Address address;
}
